---
output:
  html_document:
    theme: united
  knitrBootstrap::bootstrap_document:
    theme.chooser: TRUE
    highlight.chooser: TRUE
---

`regionReport` supplementary website
====================================

This is the supplementary website for the `regionReport` paper. 

# Example use cases

## `bumphunter` case

An example using [bumphunter](http://bioconductor.org/packages/release/bioc/html/bumphunter.html) is showcased at [bumphunter.html](/regionReportSupp/bumphunter.html). This file shows the code for obtaining a set of simulated differentially methylated regions and creating a HTML report using `renderReport()`. The report is a bit simpler than the one in the example of `renderReport()` because there is no p-value variable. The output report from this example is available at [bumphunter-example](/regionReportSupp/bumphunter-example/index.html).


## `DiffBind` case

An example using [DiffBind](http://bioconductor.org/packages/release/bioc/html/DiffBind.html) is showcased at [DiffBind.html](/regionReportSupp/DiffBind.html). This file shows the code for obtaining a set of differentially bounded sites and creating a HTML report using `renderReport()` with custom code to create a MA plot and two PCA plots. The output report from this example is available at [DiffBind-example](/regionReportSupp/DiffBind-example/index.html).

## `derfinder` cases

This section uses three different data sets as described in the `derfinder` paper ([bioRxiv preprint](http://biorxiv.org/content/early/2015/02/19/015370)).

The three reports can be viewed following these links:

* [brainspan](/regionReportSupp/brainspan/basicExploration.html)
* [hippo](/regionReportSupp/hippo/basicExploration.html)
* [simulation](/regionReportSupp/simulation/basicExploration.html)

Note that each report is around 40-50 MB in size and can take some time to load.

The code used for generating these reports is available at the `derfinder` paper ([bioRxiv preprint](http://biorxiv.org/content/early/2015/02/19/015370)) supplementary website [derSoftware](http://lcolladotor.github.io/regionReportSupp/).


# Misc

[genomicRanges.R](/regionReportSupp/genomicRanges.R) has simple code for determining how many unique packages depend, import or suggest `GenomicRanges`.
